### PR TITLE
Reflect overall success/failure in favicon indicator

### PR DESCRIPTION
**Pull request by tsibley**
Useful for seeing the state of things at a glance.  Inspired by GitHub's similar behaviour.

For now, the "success" indicator doesn't mean nothing's amiss (e.g. that recent runs have completed, that nothing's been cancelled, etc.), just that nothing's failed.  We may want to make this more nuanced in the future, but that requires additional favicon states that I'm not inclined to produce right now.

favicon.svg is now a (Inkscape) source file that's no longer copied as-is but instead used to produce multiple build/favicon-*.svg outputs by selective inclusion of layers.  The sparse index page gets a "?" indicator in the favicon to suggest "status" without suggesting "all's well" or "something's wrong".  There's probably some better indicator here, but it seems good enough for now.

I suspect this will make us want to clean up old lingering failed runs from the status page… ;)

## Checklist

- [x] Checks pass

### CODE REVIEW

**Review by genehack — APPROVED** [review]

**Comment by joverlee521** [comment]
> I suspect this will make us want to clean up old lingering failed runs from the status page… ;)

Would it make sense to limit the overall success/failure to the last ~24-48 hours? I've ignored the old lingering failures if the next automated run completed successfully. Seems like a waste to re-run workflows just for the ✅

**Comment by tsibley** [comment]
Fixed up, but uh, what now GitHub?

image

**Comment by tsibley** [comment]
Right, but that's already ignored by the "last run" consideration. It doesn't require a 24-48 hour recency condition. I'm talking about things like this:

image

**Comment by tsibley** [comment]
Maybe it's not clear that

https://github.com/nextstrain/status/blob/1a895066c65a428bc4256f76463104794d7c7636/pathogen-workflows.html.js#L32-L37

is only considering the last run of each workflow in each repo?

**Comment by tsibley** [comment]
Like, maybe I should have written:

```js
const someFailure = 
  runsByRepoAndWorkflow 
    .flatMap(([, workflows]) => 
      workflows.map(([, [lastRun, ]]) => 
        lastRun.conclusion ?? lastRun.status)) 
    .some(x => x === "failure"); 
```

or

```js
const someFailure = 
  runsByRepoAndWorkflow 
    .flatMap(([, workflows]) => 
      workflows.map(([, runs]) => 
        runs[0].conclusion ?? runs[0].status)) 
    .some(x => x === "failure"); 
```

**Comment by joverlee521** [comment]
> Right, but that's already ignored by the "last run" consideration.

Ah gotcha, yeah, totally missed this was only considering the last run!

However, the lassa example is an interesting case...I'm pretty sure it was just a manual test run that was later fixed for the automated run.

**Comment by tsibley** [comment]
Yeah. The lassa example will also fall off the 90 day cliff

https://github.com/nextstrain/status/blob/72803ecc7e0c77214dd26ac59fc68567ce1c5a01/pathogen-workflows.sql#L128-L129

on 24 Dec.

I will say that in general, I find the Ingest / Phylo / Ingest to Phylo pattern a bit weird (though I understand why it's that way currently).

**Comment by tsibley** [comment]
> Like, maybe I should have written…

Repushed with the second take to hopefully make it clearer.

**Comment by joverlee521** [comment]
Since merging there's been two workflow runs with the inkscape error, but other runs completed successfully.

https://github.com/nextstrain/status/actions/runs/11821865530/job/32937840090:
```
< favicon.svg \
  inkscape --pipe --export-plain-svg --export-area-page --export-filename - \
| ./favicon-'[layer]'.svg.py success \
> favicon-success.svg
bash: line 1: inkscape: command not found
Traceback (most recent call last):
  File "/home/runner/work/status/status/./favicon-[layer].svg.py", line 7, in <module>
    doc = ET.parse(stdin)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
make: *** [Makefile:18: favicon-success.svg] Error 1
make: *** Deleting file 'favicon-success.svg'
```

https://github.com/nextstrain/status/actions/runs/11822605189/job/32940011673:
```
< favicon.svg \
  inkscape --pipe --export-plain-svg --export-area-page --export-filename - \
| ./favicon-'[layer]'.svg.py failure \
> favicon-failure.svg
bash: line 1: inkscape: command not found
Traceback (most recent call last):
  File "/home/runner/work/status/status/./favicon-[layer].svg.py", line 7, in <module>
    doc = ET.parse(stdin)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
make: *** [Makefile:18: favicon-failure.svg] Error 1
make: *** Deleting file 'favicon-failure.svg'
```

**Comment by joverlee521** [comment]
There's been a [mix of successful and failure runs](https://github.com/nextstrain/status/actions/workflows/ci.yaml)...why does make sometimes recognize the committed favicon files but will run the `favicon-%.svg` rule other times?

**Comment by joverlee521** [comment]
> why does make sometimes recognize the committed favicon files but will run the favicon-%.svg rule other times?

Hmm, is there a chance that this is due to the timing/order in which the files are downloaded from the repository during `actions/checkout`? If `favicon.svg` was downloaded one second _after_ the `favicon-*.svg` files, then make sees the `favicon-*.svg` file as outdated and runs the rule. 

Should we update the [make command](https://github.com/nextstrain/status/blob/7a23f7895a99c4c23b5853089661f07ddcfaf44a/.github/workflows/ci.yaml#L34) to ensure that the `favicon-%.svg` rule never runs during CI?

```
make -o favicon.svg -o 'favicon-[layer].svg.py'
```

**Comment by tsibley** [comment]
Ugh. Maybe? Good spotting.

**Comment by tsibley** [comment]
https://github.com/nextstrain/status/pull/30

**Pull request merged**
